### ISSUE TITLE
[Errno -9981] Input overflowed         follow by             [Errno -9988] Stream closed

### ISSUE THREAD

**Issue by YBIacous** [SuperShinyEyes/spl-meter-with-RPi#2]
Hello,
I ran in the same problem as servas089 (He solve his problem with [https://raspberrypi.stackexchange.com/questions/47045/hcitool-scan-says-no-such-device]).

First reading fine (read the dB(A) correctly) then Error Input overflowed follow by Error stackhoverflow

_(1) Error recording: [Errno -9981] Input overflowed
(2) Error recording: [Errno -9988] Stream closed
(3) Error recording: [Errno -9988] Stream closed
Traceback (most recent call last):
File "/home/pi/Bureau/spl-meter-with-RPi-master/spl_meter.py", line 116, in
listen()
File "/home/pi/Bureau/spl-meter-with-RPi-master/spl_meter.py", line 91, in listen
print(" (%d) Error recording: %s" % (error_count, e))
File "/usr/lib/python2.7/idlelib/PyShell.py", line 1356, in write
return self.shell.write(s, self.tags)
KeyboardInterrupt_

The code is not tweaked, on Pi 2 B. I try a lot of Chunk and Rate number with no sucess.

There is a USB microphone plug to the Pi (the first reading varie according to the noise, so I assume the microphone is not faulty ?).

I really a # noob at Pi and programming but good in Acoustics.

I installed all the prerequisite (pyaudio, selenium, etc) but I don't know if I must take the new one or the prerequisite with theyre version number.

I am very sorry to bother you, I think it's my poor knowledge of the programming and Pi stuff that lead me to this point.

It seem that servas089 as a Pi 3, let me know if you think that I must buy a Pi 3 instead of a Pi 2.

All help will be very appreciated

Yannick

For more information there is the Python consol output:

====== RESTART: /home/pi/Bureau/spl-meter-with-RPi-master/spl_meter.py ======
Listening
A-weighted: +24.10 dB
update_max_if_new_is_larger_than_max called
max observed
(1) Error recording: [Errno -9981] Input overflowed
(2) Error recording: [Errno -9988] Stream closed
(3) Error recording: [Errno -9988] Stream closed

Traceback (most recent call last):
File "/home/pi/Bureau/spl-meter-with-RPi-master/spl_meter.py", line 116, in
listen()
File "/home/pi/Bureau/spl-meter-with-RPi-master/spl_meter.py", line 91, in listen
print(" (%d) Error recording: %s" % (error_count, e))
File "/usr/lib/python2.7/idlelib/PyShell.py", line 1356, in write
return self.shell.write(s, self.tags)
KeyboardInterrupt

**And for more information**
Pi 2B
pi@raspberrypi:~ $ cat /proc/asound/cards
0 [ALSA ]: bcm2835 - bcm2835 ALSA
bcm2835 ALSA
1 [Device ]: USB-Audio - USB PnP Sound Device
C-Media Electronics Inc. USB PnP Sound Device at usb-3f980000.usb-1.5, full spe

**Comment by SuperShinyEyes** [comment]
Hi,

Thanks for opening the ticket. I'm currently busy as I started a new job. 
I may be able to come back to it in two weeks. :)

**Comment by SuperShinyEyes** [comment]
This is embarrassing but I cannot even run 
```
pip install -r requirements
```
I get the error:
```
Command "/home/pi/venv-spl-meter/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-cEgKtc/PyAudio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-bo2Ip5-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/venv-spl-meter/include/site/python2.7/PyAudio" failed with error code 1 in /tmp/pip-build-cEgKtc/PyAudio/
```
Which Raspbian are you using and how did you install all the dependencies?

**Comment by SuperShinyEyes** [comment]
I spent enough time during the weekend,

- I didn't manage to fully reproduce my project
	- selenium and geckodriver issue was not easily solvable.
- I made non-gui version working
	- based on this, I assume you have maybe set CHUNK value set too small. Try to make it larger such as 9600 or even larger.

I made a docker image for the non-gui version so you can just test it out,

```bash
# Run this command at the project dir
# Pull the image
docker pull shinyeyes/rpi-spl-meter:v0.1

# Enter the container
docker run -it --privileged -v /dev/bus/usb:/dev/bus/usb shinyeyes/rpi-spl-meter:v0.1

# Run this command in the container
$HOME/miniconda/envs/spl-meter/bin/python spl_meter_text.py
```

Cheers,

**Comment by YBIacous** [comment]
Hello,

Thank you, I will try this evening and report back.

I was three days away, sorry for not responding.

**Comment by fers50** [comment]
can this code to raspberry pi 3?

**Comment by YBIacous** [comment]
Hello,
Long time sorry.
I can't pull the image. The Docker return error as:

`pi@raspberrypi:~/spl-meter-with-RPi-master $ sudo docker run -it --privileged -v /dev/bus/usb:/dev/bus/usb shinyeyes/rpi-spl-meter:v0.1
Unable to find image 'shinyeyes/rpi-spl-meter:v0.1' locally
docker: Error response from daemon: manifest for shinyeyes/rpi-spl-meter:v0.1 not found.
See 'docker run --help'.`

Or
`pi@raspberrypi:~/spl-meter-with-RPi-master $ sudo docker pull shinyeyes/rpi-spl-meter:v0.1
Error response from daemon: manifest for shinyeyes/rpi-spl-meter:v0.1 not found
`

I am little a newbie but I can't get past this error.

Is ther any chance that you can help me further?

Thank a lot

**Comment by SuperShinyEyes** [comment]
Hi, 

I'm sorry but I pulled down the image for some reason. 
I don't have the time to build the image now. 
Maybe in June...

**Comment by YBIacous** [comment]
Hello,
Nous problem. I can wait, don't worry.

Finally I went to cheap soundmeter, testing some model for now. They run
fine for the time.

But, if I can do it with cheap micro that will be ok.

Waiting June.

Regards
